# Generated by Django 4.2.3 on 2023-08-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_subscribedusers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
