# Generated by Django 4.2.3 on 2023-08-15 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_subscribedusers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date create,d'),
        ),
    ]
