# Generated by Django 4.2.3 on 2023-08-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_subscribedusers_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
