# Generated by Django 4.2.3 on 2023-08-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_subscribedusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedusers',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='subscribedusers',
            name='name',
        ),
    ]
